version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: reviews
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: reviews

	reviews:
		build: .
		image: chamaconekt/reviews
		links:
		- postgres
		container_name: reviews
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- reviews
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/reviews-nginx/nginx.conf
		depends_on:
			- reviews
		ports:
			- 80:80
		volumes_from:
			- reviews

volumes:
	reviews-static-files:
		driver:local